filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

#setup.kibana:
#  host: http://13.67.57.169:5601
#  username: elastic
#  password: youpassword

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  username: ary
  password: test123
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"